In [4]:
import numpy as np
A = np.array([[1,2,3], [4,5,6],[7,8,9]]) 
A.size

9

In [5]:
A.shape

(3, 3)

In [10]:
data_list = [
    [ 0,  1,  2,  3,  4],
    [10, 11, 12, 13, 14],
    [20, 21, 22, 23, 24],
]
data_np = np.array(data_list)
data_np[2,1:4]

array([21, 22, 23])

In [12]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.sum(A, axis=0)  

array([12, 15, 18])

In [13]:
np.sum(A, axis=1)

array([ 6, 15, 24])

In [18]:
A = np.array([[1,2,3], \
              [4,5,6], \
              [7,8,9]]) 
A[A >= 7] = 123

In [19]:
A

array([[  1,   2,   3],
       [  4,   5,   6],
       [123, 123, 123]])

In [23]:
import pandas as pd
#s = pd.Series(data=[1,2,'three'], index=['id1', 'id2', 'id3'])
s = pd.Series({'id1': 1, 'id2': 2, 'id3': 'three'})
s

id1        1
id2        2
id3    three
dtype: object

In [ ]:
pd.read
pd.read_csv