# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import pandas as pd
import numpy as np


# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents. Load the data from [here](https://drive.google.com/file/d/1AmdvTSj5Fl86i4uHiOnZPFg8S8mAIreA/view?usp=sharing) and place it in the data folder

In [2]:
# Your code here:
salaries=pd.read_csv('../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [3]:
# Your code here:
salaries.head()

Name                              Job Titles  \
0    AARON,  JEFFERY M                                SERGEANT   
1      AARON,  KARINA   POLICE OFFICER (ASSIGNED AS DETECTIVE)   
2  AARON,  KIMBERLEI R                CHIEF CONTRACT EXPEDITER   
3  ABAD JR,  VICENTE M                       CIVIL ENGINEER IV   
4    ABASCAL,  REECE E             TRAFFIC CONTROL AIDE-HOURLY   

         Department Full or Part-Time Salary or Hourly  Typical Hours  \
0            POLICE                 F           Salary            NaN   
1            POLICE                 F           Salary            NaN   
2  GENERAL SERVICES                 F           Salary            NaN   
3       WATER MGMNT                 F           Salary            NaN   
4              OEMC                 P           Hourly           20.0   

   Annual Salary  Hourly Rate  
0       101442.0          NaN  
1        94122.0          NaN  
2       101592.0          NaN  
3       110064.0          NaN  
4            NaN        19.86

In [4]:
salaries.rename(columns={'Hourly Rate': 'Hourly_Rate'}, inplace=True)

We see from looking at the `head` function that there is quite a bit of missing data. Let's examine how much missing data is in each column. Produce this output in the cell below

In [5]:
# Your code here:
salaries.isnull().sum()

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        25161
Annual Salary         8022
Hourly_Rate          25161
dtype: int64

Let's also look at the count of hourly vs. salaried employees. Write the code in the cell below

In [6]:
# Your code here:
salaries['Salary or Hourly'].count()

33183

What this information indicates is that the table contains information about two types of employees - salaried and hourly. Some columns apply only to one type of employee while other columns only apply to another kind. This is why there are so many missing values. Therefore, we will not do anything to handle the missing values.

There are different departments in the city. List all departments and the count of employees in each department.

In [7]:
copied=salaries.copy() #making a copy of the dataframe so that we do not interfere with the original
copied.drop(['Job Titles','Full or Part-Time','Salary or Hourly','Typical Hours','Annual Salary','Hourly_Rate'],axis='columns',inplace=True)

In [8]:
# Your code here:
copied.groupby('Department').count()


Name
Department                  
ADMIN HEARNG              39
ANIMAL CONTRL             81
AVIATION                1629
BOARD OF ELECTION        107
BOARD OF ETHICS            8
BUDGET & MGMT             46
BUILDINGS                269
BUSINESS AFFAIRS         171
CITY CLERK                84
CITY COUNCIL             411
COMMUNITY DEVELOPMENT    207
COPA                     116
CULTURAL AFFAIRS          65
DISABILITIES              28
DoIT                      99
FAMILY & SUPPORT         615
FINANCE                  560
FIRE                    4641
GENERAL SERVICES         980
HEALTH                   488
HUMAN RELATIONS           16
HUMAN RESOURCES           79
INSPECTOR GEN             87
LAW                      407
LICENSE APPL COMM          1
MAYOR'S OFFICE            85
OEMC                    2102
POLICE                 13414
POLICE BOARD               2
PROCUREMENT               92
PUBLIC LIBRARY          1015
STREETS & SAN           2198
TRANSPORTN              1140
TREASURER                 22
WATER MGMNT             1879

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [9]:
hourly_salaries=salaries.copy()

In [10]:
hourly_salaries.dropna(subset=['Hourly_Rate'], inplace=True)

In [11]:
# Your code here:

import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
from scipy.stats import ttest_1samp
import numpy as np
from scipy.stats import norm

from scipy.stats import t
import matplotlib.pyplot as plt
sns.set_style("darkgrid") 

Null hypothesis and alternative hypothesis

Ha: the average hourly wage for all hourly workers ≠$30/hr.

H0: the average hourly wage for all hourly workers = $30/hr. 

In [12]:
hourly=hourly_salaries['Hourly_Rate']

In [13]:
hourly.max()

109.0

In [14]:
hourly.min()

2.65

In [15]:
hourly_mean = hourly.mean()
mu = 30
sample_stdev = hourly.std()
standard_error = sample_stdev / np.sqrt(len(hourly))

In [16]:
t_value = (hourly_mean - mu) / standard_error
print(t_value)

20.619805785501907


In [17]:
from scipy.stats import t

df = len(hourly) - 1
mean, var, skew, kurt = t.stats(df, moments='mvsk')

In [18]:
# retrieve value <= probability
alpha = 0.025
alpha = 1 - alpha
alpha = t.ppf(alpha, hourly)
print(alpha)
# confirm with cdf

[2.08690653 2.01277777 2.02888554 ... 2.02888554 2.0124855  2.00973133]


In [19]:
t, p = ttest_1samp(hourly, 30)
print(t)
print(p)

20.6198057854942
4.3230240486229894e-92


Since the p-value is extremely low, we can reject the following null hypothesis:
    H0: the average hourly wage for all hourly workers = $30/hr. 

We are also curious about salaries in the police force. The chief of police in Chicago claimed in a press briefing that salaries this year are higher than last year's mean of $86000/year a year for all salaried employees. Test this one sided hypothesis using a 95% confidence interval.

Hint: A one tailed test has a p-value that is half of the two tailed p-value. If our hypothesis is greater than, then to reject, the test statistic must also be positive.

Null hypothesis and alternative hypothesis

H0: the average salary for all police force = $86000/year.

Ha: the average salary for all police force ≠ $86000/year. 


In [20]:
annual_salaries=salaries.copy()
annual_salaries.dropna(subset=['Annual Salary'], inplace=True)

In [21]:
# Your code here:
police = annual_salaries[annual_salaries['Department']=="POLICE"] 

In [22]:
police_sal=police['Annual Salary']

In [23]:
police_sal.max()

260004.0

In [24]:
police_sal.min()

38376.0

In [25]:
police_mean = police_sal.mean()
mu = 86000
sample_stdev = police_sal.std()
standard_error = sample_stdev / np.sqrt(len(police_sal))

In [26]:
t_value = (police_mean - mu) / standard_error
print(t_value)

3.08199700571315


In [27]:
from scipy.stats import t

df = len(police_sal) - 1
mean, var, skew, kurt = t.stats(df, moments='mvsk')

In [28]:
# retrieve value <= probability
alpha = 0.05
alpha = 1 - alpha
alpha = t.ppf(alpha, police_sal)
print(alpha)
# confirm with cdf

[1.64486865 1.64486982 1.64486995 ... 1.64488532 1.64487055 1.64486995]


In [29]:
t, p = ttest_1samp(police_sal, 86000)
print(t)
print(p)

3.081997005712994
0.0020603403550965137


Since the p-value is 0.002 <0.05, we can reject the following null hypothesis:H0: the average salary for all police force = $86000/year. 

Using the `crosstab` function, find the department that has the most hourly workers. 

In [30]:
# Your code here:
most_hourly=pd.crosstab(salaries.Hourly_Rate,salaries.Department)
most_hourly=most_hourly.sum(axis = 0, skipna = True) 
most_hourly.sort_values(axis=0,ascending=False)

Department
STREETS & SAN            1862
WATER MGMNT              1513
OEMC                     1273
AVIATION                 1082
GENERAL SERVICES          765
TRANSPORTN                725
PUBLIC LIBRARY            299
FAMILY & SUPPORT          287
CITY COUNCIL               64
FINANCE                    44
LAW                        40
ANIMAL CONTRL              19
POLICE                     10
MAYOR'S OFFICE              8
CULTURAL AFFAIRS            7
BUSINESS AFFAIRS            7
COMMUNITY DEVELOPMENT       4
HUMAN RESOURCES             4
HEALTH                      3
FIRE                        2
PROCUREMENT                 2
BUDGET & MGMT               2
dtype: int64

Streets and Sanitation is the department with the most hourly workers

The workers from the department with the most hourly workers have complained that their hourly wage is less than $35/hour. Using a one sample t-test, test this one-sided hypothesis at the 95% confidence level.

Null hypothesis and alternative hypothesis

H0: the average hourly wage for Streets and Sanitation = $35/hr.

Ha: the average hourly wage for Streets and Sanitation < $35/hr. 

In [31]:
# Your code here:
hourly_salaries=salaries.copy()
hourly_salaries.dropna(subset=['Hourly_Rate'], inplace=True)



In [32]:
streets = hourly_salaries[hourly_salaries['Department']=="STREETS & SAN"] 

In [33]:
streets_sal=streets['Hourly_Rate']

In [34]:
streets_sal.max()

53.1

In [35]:
streets_sal.min()

19.5

In [36]:
streets_mean = streets_sal.mean()
mu = 35
sample_stdev = streets_sal.std()
standard_error = sample_stdev / np.sqrt(len(streets_sal))

In [37]:
t_value = (streets_mean - mu) / standard_error
print(t_value)

-9.567447887851964


In [38]:
from scipy.stats import t

df = len(streets_sal) - 1
mean, var, skew, kurt = t.stats(df, moments='mvsk')

In [39]:
# retrieve value <= probability
alpha = 0.05
alpha = 1 - alpha
alpha = t.ppf(alpha, streets_sal)
print(alpha)
# confirm with cdf

[1.68879879 1.71915257 1.68879879 ... 1.68879879 1.68803919 1.71673534]


In [40]:
t, p = ttest_1samp(streets_sal, 35)
print(t)
print(p)

-9.567447887848152
3.3378530564707717e-21


Since the p-value is extremely low, we can reject the following null hypothesis:H0: the average hourly wage for Streets and Sanitation = $35/hr. 


# Challenge 3: To practice - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [41]:
# Your code here:

In [42]:
hourly=hourly_salaries['Hourly_Rate']

from scipy.stats import t

df = len(hourly) - 1
mean, var, skew, kurt = t.stats(df, moments='mvsk')

In [43]:
confidence_level = 0.95
DoF = len(hourly)-1
sample_mean = hourly.mean()
sample_std = hourly.std()

standard_error = stats.sem(hourly, axis=None, ddof=1)
t = stats.t.interval(confidence_level,DoF)[1]

lower,upper = ((sample_mean - (t * standard_error)),(sample_mean + (t*standard_error)))
print(f"The confidence interval for the hourly wage of employees is from {lower} to {upper}, with confidence level of {confidence_level}.")

The confidence interval for the hourly wage of employees is from 32.52345834488529 to 33.05365708767727, with confidence level of 0.95.


In [44]:
#stats.sem(hourly, axis=None, ddof=1)

Now construct the 95% confidence interval for all salaried employeed in the police in the cell below.

In [45]:
annual_salaries=salaries.copy()
annual_salaries.dropna(subset=['Annual Salary'], inplace=True)

In [46]:
police = annual_salaries[annual_salaries['Department']=="POLICE"] 

In [47]:
police_sal=police['Annual Salary']

from scipy.stats import t

df = len(police_sal) - 1
mean, var, skew, kurt = t.stats(df, moments='mvsk')

In [48]:
# Your code here:
confidence_level = 0.95
DoF = len(police_sal)-1
sample_mean = police_sal.mean()
sample_std = police_sal.std()

standard_error = stats.sem(police_sal, axis=None, ddof=1)
t = stats.t.interval(confidence_level,DoF)[1]

lower,upper = ((sample_mean - (t * standard_error)),(sample_mean + (t*standard_error)))
print(f"The confidence interval for the annual salary of employees in the police force is from {lower} to {upper}, with confidence level of {confidence_level}.")


The confidence interval for the annual salary of employees in the police force is from 86177.05631531784 to 86795.77269094894, with confidence level of 0.95.


# Bonus Challenge - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [49]:
# Your code here:

