# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [28]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [29]:
# your code here
print(np.__version__)

1.18.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [30]:
# Method 1
a = np.random.random((2,3,5))
print(a)

#[tjerk] yes

[[[0.02696521 0.14654883 0.81311007 0.39362067 0.07836128]
  [0.24444599 0.80096254 0.56471843 0.21077902 0.33631574]
  [0.29794642 0.35150763 0.83046128 0.22366454 0.97652975]]

 [[0.08723899 0.3460605  0.95647568 0.13741414 0.64575319]
  [0.90659608 0.24726514 0.982724   0.43868654 0.09411069]
  [0.28980554 0.33343436 0.87037085 0.52619806 0.67856927]]]


In [31]:
# Method 2
a = np.random.randint(1000, size = (2, 3, 5))
print(a)


#[tjerk] yes

[[[399 887 235 821 524]
  [676 574 292 874 781]
  [554 734 875 607 748]]

 [[662 296 604 327 325]
  [ 60 909 247 737 132]
  [991 983 819 726 884]]]


In [32]:
# Method 3

a_1 = np.random.choice((100), size = (2, 3, 5))
print(a)

#[tjerk] yes

[[[399 887 235 821 524]
  [676 574 292 874 781]
  [554 734 875 607 748]]

 [[662 296 604 327 325]
  [ 60 909 247 737 132]
  [991 983 819 726 884]]]


#### 4. Print *a*.


In [33]:
# your code here
print(a)

[[[399 887 235 821 524]
  [676 574 292 874 781]
  [554 734 875 607 748]]

 [[662 296 604 327 325]
  [ 60 909 247 737 132]
  [991 983 819 726 884]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [34]:
# your code here
b = np.random.random((5, 2, 3))
b /= np.sum(b)

#[tjerk] no, i think you have overlooked 'with all values equaling 1'

#### 6. Print *b*.


In [35]:
# print the array
print(b)
#check if sum == 1
b.sum()

[[[0.01608632 0.03962614 0.01632127]
  [0.03977546 0.02401437 0.03222495]]

 [[0.01066328 0.0575568  0.06242923]
  [0.05085747 0.06169357 0.00105967]]

 [[0.04127194 0.03896549 0.00378067]
  [0.06140156 0.01735338 0.02815033]]

 [[0.04246003 0.04221928 0.03652005]
  [0.00744444 0.02322925 0.0054511 ]]

 [[0.02245441 0.04612779 0.04381252]
  [0.04553279 0.03229302 0.04922343]]]


0.9999999999999998

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [36]:
# your code here
# Comparing the size of randomly generated array A and randomonly
# generated but limited to sum == 1, array B.
if np.size(a) == np.size(b):
    print(True)
else:
    print(False)
    
#[tjerk] yes, or a bit shorter in just one line
#print(np.size(a) == np.size(b))

True


In [37]:
print(np.size(a) == np.size(b))

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [38]:
# your answer here
# No, the shapes are different. A Value error pops up:
    #ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
# np.add(a,b)

#[tjerk] yes

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [39]:
# your code here
c = b.reshape(2, 3, 5)
print(c)

[[[0.01608632 0.03962614 0.01632127 0.03977546 0.02401437]
  [0.03222495 0.01066328 0.0575568  0.06242923 0.05085747]
  [0.06169357 0.00105967 0.04127194 0.03896549 0.00378067]]

 [[0.06140156 0.01735338 0.02815033 0.04246003 0.04221928]
  [0.03652005 0.00744444 0.02322925 0.0054511  0.02245441]
  [0.04612779 0.04381252 0.04553279 0.03229302 0.04922343]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [40]:
# your code/answer here
d = np.add(a, c)
# the arrays share the same shape hence the values can be added

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [41]:
# your code/answer here
print(a,d)

#[tjerk] where is your explanation? please answer all questions!

[[[399 887 235 821 524]
  [676 574 292 874 781]
  [554 734 875 607 748]]

 [[662 296 604 327 325]
  [ 60 909 247 737 132]
  [991 983 819 726 884]]] [[[399.01608632 887.03962614 235.01632127 821.03977546 524.02401437]
  [676.03222495 574.01066328 292.0575568  874.06242923 781.05085747]
  [554.06169357 734.00105967 875.04127194 607.03896549 748.00378067]]

 [[662.06140156 296.01735338 604.02815033 327.04246003 325.04221928]
  [ 60.03652005 909.00744444 247.02322925 737.0054511  132.02245441]
  [991.04612779 983.04381252 819.04553279 726.03229302 884.04922343]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [42]:
# your code here
e = np.multiply(a,c)
print(e)

[[[ 6.41844312 35.14838859  3.83549836 32.65565609 12.58353044]
  [21.78406845  6.12072038 16.80658423 54.56314644 39.71968234]
  [34.17823661  0.77779617 36.11294916 23.652051    2.82793977]]

 [[40.64783163  5.13660175 17.00280017 13.88443005 13.72126665]
  [ 2.1912029   6.76699201  5.73762467  4.01745747  2.96398238]
  [45.71263832 43.06770258 37.29135741 23.44473413 43.51350939]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [43]:
# your code/answer here
a == e
# No, because a multiplication to the values of a was added.

#[tjerk] something went wrong because they should be the same
# i found your bug, you did random instead of ones. so that mistake propagated to having this answer wrong

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [44]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max,d_min,d_mean)

991.0461277884116 60.03652004828412 609.4666666666667


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [45]:
# your code here
f = np.empty((2, 3, 5))
print(f)

[[[ 6.41844312 35.14838859  3.83549836 32.65565609 12.58353044]
  [21.78406845  6.12072038 16.80658423 54.56314644 39.71968234]
  [34.17823661  0.77779617 36.11294916 23.652051    2.82793977]]

 [[40.64783163  5.13660175 17.00280017 13.88443005 13.72126665]
  [ 2.1912029   6.76699201  5.73762467  4.01745747  2.96398238]
  [45.71263832 43.06770258 37.29135741 23.44473413 43.51350939]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [46]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

f

#[tjerk] yes, very creative indexing

array([[[ 25.,  75.,  25.,  75.,  25.],
        [ 75.,  25.,  25.,  75.,  75.],
        [ 25.,  75.,  75.,  25.,  75.]],

       [[ 75.,  25.,  25.,  25.,  25.],
        [  0.,  75.,  25.,  75.,  25.],
        [100.,  75.,  75.,  75.,  75.]]])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [47]:
# your code here
print(d)
print(f)

#[tjerk] looks like you aced it!
#my tip is to really read the assignment well
#and to have a lot of fun in Disneyland

[[[399.01608632 887.03962614 235.01632127 821.03977546 524.02401437]
  [676.03222495 574.01066328 292.0575568  874.06242923 781.05085747]
  [554.06169357 734.00105967 875.04127194 607.03896549 748.00378067]]

 [[662.06140156 296.01735338 604.02815033 327.04246003 325.04221928]
  [ 60.03652005 909.00744444 247.02322925 737.0054511  132.02245441]
  [991.04612779 983.04381252 819.04553279 726.03229302 884.04922343]]]
[[[ 25.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  25.  25.  25.  25.]
  [  0.  75.  25.  75.  25.]
  [100.  75.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [48]:
# your code here