# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [3]:
# your code here

myNumpy = np

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
# Method 1
a = np.random.random((2,3,5))

In [0]:
# Method 2
#Francesca : I can't think of any other method other than the above. 
a = np.random.randit(2,3,5,(4,5))

#[tjerk: you were very close and missed a N, ITS RANDINT, are you aware of documentation? try googling 'numpy documentation random 

TypeError: data type not understood

In [0]:
# Method 3

#### 4. Print *a*.


In [9]:
# your code here
print(a)

[[[0.77193672 0.38018065 0.53412972 0.01940588 0.55948771]
  [0.07837214 0.85349699 0.75127042 0.10014048 0.89487122]
  [0.68495425 0.5284024  0.17829434 0.54540141 0.74043524]]

 [[0.01054772 0.89348909 0.58148596 0.78402931 0.82472584]
  [0.35982968 0.04670164 0.94052742 0.42554756 0.3203189 ]
  [0.69364404 0.73767597 0.17426593 0.85199841 0.00602986]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [10]:
# your code here

b=np.ones((5,2,3))

#### 6. Print *b*.


In [11]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [14]:
# your code here
#Francesca = Is this right? What am I doing incorrectly? 

n = min(len(a), len(b))

out_idx = np.flatnonzero(a[:n] == b[:n])
out_val = a[out_idx]

#[tjerk] creative but it is not right, nice try though!
#you were thinking way to difficult
#its just print(a.size == b.size);
#the == compares the two sizes and returns TRUE if the sizes are correct
#


<ipython-input-14-d98e622a5278>:4: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  out_idx = np.flatnonzero(a[:n] == b[:n])


array([], dtype=int64)

#### 8. Are you able to add *a* and *b*? Why or why not?


In [18]:
# your answer here
np.sum(a,b) 
#Francesca : is it because each has a different size? 


#[tjerk yes you are right!! you cannot add if the same doesnt match]

TypeError: only integer scalar arrays can be converted to a scalar index

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [34]:
import numpy as np #Francesca : I can't seem to assign "c" in this new formula  
b = np.arange(30).reshape(2,3,5)
print(b)

# [tjerk: nice that you use reshape]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [36]:
d = np.concatenate((a,b))
print(d)

#[tjerk: adding is something else than concatenating, what is the difference?]

[[[7.71936717e-01 3.80180654e-01 5.34129722e-01 1.94058819e-02
   5.59487714e-01]
  [7.83721419e-02 8.53496987e-01 7.51270425e-01 1.00140479e-01
   8.94871219e-01]
  [6.84954251e-01 5.28402396e-01 1.78294344e-01 5.45401408e-01
   7.40435241e-01]]

 [[1.05477206e-02 8.93489090e-01 5.81485957e-01 7.84029307e-01
   8.24725838e-01]
  [3.59829685e-01 4.67016398e-02 9.40527423e-01 4.25547565e-01
   3.20318901e-01]
  [6.93644042e-01 7.37675966e-01 1.74265934e-01 8.51998405e-01
   6.02985519e-03]]

 [[0.00000000e+00 1.00000000e+00 2.00000000e+00 3.00000000e+00
   4.00000000e+00]
  [5.00000000e+00 6.00000000e+00 7.00000000e+00 8.00000000e+00
   9.00000000e+00]
  [1.00000000e+01 1.10000000e+01 1.20000000e+01 1.30000000e+01
   1.40000000e+01]]

 [[1.50000000e+01 1.60000000e+01 1.70000000e+01 1.80000000e+01
   1.90000000e+01]
  [2.00000000e+01 2.10000000e+01 2.20000000e+01 2.30000000e+01
   2.40000000e+01]
  [2.50000000e+01 2.60000000e+01 2.70000000e+01 2.80000000e+01
   2.90000000e+01]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [38]:
# your code/answer here
#Francesca : Because d's values contain the concatenated value of a + b (because I couldn't assign c)
print(a,d)

[[[0.77193672 0.38018065 0.53412972 0.01940588 0.55948771]
  [0.07837214 0.85349699 0.75127042 0.10014048 0.89487122]
  [0.68495425 0.5284024  0.17829434 0.54540141 0.74043524]]

 [[0.01054772 0.89348909 0.58148596 0.78402931 0.82472584]
  [0.35982968 0.04670164 0.94052742 0.42554756 0.3203189 ]
  [0.69364404 0.73767597 0.17426593 0.85199841 0.00602986]]] [[[7.71936717e-01 3.80180654e-01 5.34129722e-01 1.94058819e-02
   5.59487714e-01]
  [7.83721419e-02 8.53496987e-01 7.51270425e-01 1.00140479e-01
   8.94871219e-01]
  [6.84954251e-01 5.28402396e-01 1.78294344e-01 5.45401408e-01
   7.40435241e-01]]

 [[1.05477206e-02 8.93489090e-01 5.81485957e-01 7.84029307e-01
   8.24725838e-01]
  [3.59829685e-01 4.67016398e-02 9.40527423e-01 4.25547565e-01
   3.20318901e-01]
  [6.93644042e-01 7.37675966e-01 1.74265934e-01 8.51998405e-01
   6.02985519e-03]]

 [[0.00000000e+00 1.00000000e+00 2.00000000e+00 3.00000000e+00
   4.00000000e+00]
  [5.00000000e+00 6.00000000e+00 7.00000000e+00 8.00000000e+00
 

#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [41]:
# your code here

e = np.multiply(a,b) #Francesca : 'b' because I couldn't assign c 
print(e) 
#[tjerk well done

[[[ 0.          0.38018065  1.06825944  0.05821765  2.23795086]
  [ 0.39186071  5.12098192  5.25889297  0.80112384  8.05384097]
  [ 6.84954251  5.81242636  2.13953213  7.09021831 10.36609337]]

 [[ 0.15821581 14.29582544  9.88526127 14.11252752 15.66979093]
  [ 7.19659369  0.98073444 20.6916033   9.78759398  7.68765362]
  [17.34110106 19.17957511  4.70518022 23.85595535  0.1748658 ]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [0]:
# your code/answer here

#Francesca : no. Because e is a multiplication of a and 'c'


#[tjerk, they are actually equal, check the solution and try to understand it!]

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [42]:
# your code here

d_max = np.max(d)
print('Maxium value of the array is,',d_max)
#[Tjerk] great nice print

Maxium value of the array is, 29.0


In [43]:
d_min = np.min(d)
print('Minimum value of the array is', d_min)
#[Tjerk] great nice print

Minimum value of the array is 0.0


In [44]:
d_mean = np.mean(d)
print('The mean of the array is', d_mean)
#[Tjerk] great nice print

The mean of the array is 7.504526615135097


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [46]:
# your code here

f = np.empty((2,3,5))
print(f)

[[[ 0.          0.38018065  1.06825944  0.05821765  2.23795086]
  [ 0.39186071  5.12098192  5.25889297  0.80112384  8.05384097]
  [ 6.84954251  5.81242636  2.13953213  7.09021831 10.36609337]]

 [[ 0.15821581 14.29582544  9.88526127 14.11252752 15.66979093]
  [ 7.19659369  0.98073444 20.6916033   9.78759398  7.68765362]
  [17.34110106 19.17957511  4.70518022 23.85595535  0.1748658 ]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.
**Note**: you don't have to use Numpy in this question.

In [0]:
#Francesca : what am I doing incorrectly? 

def fill_f():
    for i in leng(d):
        if [i][0] < d_mean:
            [i][0]+25, append.fill_f
        elif [i][0] >d_mean:
            [i][0]+75, append.fill_f
        
        elif[i][0]== d_mean:
            [i][0]+50, append.fill_f

print(fill_f)

In [5]:
#[tjerk]: first of all if you want to execute a function you have to call it with paranthesis
#fill_f()
#also leng doesn't exist i think you mean len
#try again with these tips and let me know if it works


# I think you tried hard and struggled a lot, therefor i will mark this lab as done. 
# But to become a pro you need to practise and try to do the lab again with my feedback and with the solutions that we will post! 

NameError: name 'leng' is not defined

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [0]:
# your code here

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [0]:
# your code here