# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))
print(a)

[[[0.24436632 0.4110992  0.9554217  0.09901926 0.4877428 ]
  [0.89100815 0.958066   0.06683232 0.69440176 0.43544276]
  [0.98845931 0.04930461 0.24905542 0.67249346 0.68906229]]

 [[0.86428527 0.56652319 0.7398499  0.06397734 0.57773291]
  [0.96060752 0.86905277 0.12083262 0.80734617 0.92755942]
  [0.76268678 0.20845626 0.03244946 0.02401333 0.73319135]]]


In [4]:
# Method 2
t = np.random.rand(2,3,5)
print(t)

[[[0.14563003 0.46846639 0.3121772  0.73504666 0.66567915]
  [0.5517321  0.75507469 0.61766168 0.27617958 0.53116793]
  [0.47506961 0.74368366 0.01126294 0.9508933  0.64057566]]

 [[0.6842503  0.01665702 0.925313   0.55389417 0.99943387]
  [0.38101751 0.74698626 0.51172129 0.76389119 0.42821064]
  [0.61188824 0.39764428 0.91853427 0.73417165 0.77880598]]]


In [5]:
# Method 3
u = np.random.choice(range(0,10000), size=(2,3,5))
print(u)
o = np.random.randint(1000, size=(2,3,5))
print(o)

[[[2663 1647 9149 7671 4339]
  [5228 8096 8687 1307 4650]
  [8003 2216 5889  743 8498]]

 [[6593 3758 7207 5246 8703]
  [9661 3028 8613 5659 5675]
  [5988 2150 7279 8266 2098]]]
[[[904 794 789 259 315]
  [ 67  86 738 558 170]
  [540 363 717 602 957]]

 [[240 739 291 388 919]
  [161 148   8 771 164]
  [641 982 155 668 464]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.24436632 0.4110992  0.9554217  0.09901926 0.4877428 ]
  [0.89100815 0.958066   0.06683232 0.69440176 0.43544276]
  [0.98845931 0.04930461 0.24905542 0.67249346 0.68906229]]

 [[0.86428527 0.56652319 0.7398499  0.06397734 0.57773291]
  [0.96060752 0.86905277 0.12083262 0.80734617 0.92755942]
  [0.76268678 0.20845626 0.03244946 0.02401333 0.73319135]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(np.size(a))
print(np.size(b))

bool(np.size(a)==np.size(b))

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

#Let's check their shapes for that first;


print(np.shape(a))
print(np.shape(b))

#Since shapes are different we can not add a and b to each other.
#Let's try..

#c = a + b #nope..

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
print(np.shape(a))
print(np.shape(b))
c = np.transpose(b,(1,2,0))   #initial bshape=(5,2,3) so b=(5 (0th element),2 (1st element),3 (2nd element)) -->(b,(1,2,0))
print(np.shape(c))

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
#d=a+c
d=np.add(a,c)

#Shapes are same, so we can do math operations between two arrays.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a)
print(d)

#1 is added over values in array a. (or vice versa - values in a is added to ones.array.)

[[[0.24436632 0.4110992  0.9554217  0.09901926 0.4877428 ]
  [0.89100815 0.958066   0.06683232 0.69440176 0.43544276]
  [0.98845931 0.04930461 0.24905542 0.67249346 0.68906229]]

 [[0.86428527 0.56652319 0.7398499  0.06397734 0.57773291]
  [0.96060752 0.86905277 0.12083262 0.80734617 0.92755942]
  [0.76268678 0.20845626 0.03244946 0.02401333 0.73319135]]]
[[[1.24436632 1.4110992  1.9554217  1.09901926 1.4877428 ]
  [1.89100815 1.958066   1.06683232 1.69440176 1.43544276]
  [1.98845931 1.04930461 1.24905542 1.67249346 1.68906229]]

 [[1.86428527 1.56652319 1.7398499  1.06397734 1.57773291]
  [1.96060752 1.86905277 1.12083262 1.80734617 1.92755942]
  [1.76268678 1.20845626 1.03244946 1.02401333 1.73319135]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

#e = a * c

e=np.multiply(a,c)
print(e)

[[[0.24436632 0.4110992  0.9554217  0.09901926 0.4877428 ]
  [0.89100815 0.958066   0.06683232 0.69440176 0.43544276]
  [0.98845931 0.04930461 0.24905542 0.67249346 0.68906229]]

 [[0.86428527 0.56652319 0.7398499  0.06397734 0.57773291]
  [0.96060752 0.86905277 0.12083262 0.80734617 0.92755942]
  [0.76268678 0.20845626 0.03244946 0.02401333 0.73319135]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(a)
print('\n'*2)
print(e)

np.array_equal(a,e)

[[[0.24436632 0.4110992  0.9554217  0.09901926 0.4877428 ]
  [0.89100815 0.958066   0.06683232 0.69440176 0.43544276]
  [0.98845931 0.04930461 0.24905542 0.67249346 0.68906229]]

 [[0.86428527 0.56652319 0.7398499  0.06397734 0.57773291]
  [0.96060752 0.86905277 0.12083262 0.80734617 0.92755942]
  [0.76268678 0.20845626 0.03244946 0.02401333 0.73319135]]]



[[[0.24436632 0.4110992  0.9554217  0.09901926 0.4877428 ]
  [0.89100815 0.958066   0.06683232 0.69440176 0.43544276]
  [0.98845931 0.04930461 0.24905542 0.67249346 0.68906229]]

 [[0.86428527 0.56652319 0.7398499  0.06397734 0.57773291]
  [0.96060752 0.86905277 0.12083262 0.80734617 0.92755942]
  [0.76268678 0.20845626 0.03244946 0.02401333 0.73319135]]]


True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
print(d)

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("\n")

print(d_max)
print(d_min)
print(d_mean)

print("\n")
print(f"Maximum value of d is {d_max}, minimum values is {d_min}, and mean of d is {d_mean}.")

[[[1.24436632 1.4110992  1.9554217  1.09901926 1.4877428 ]
  [1.89100815 1.958066   1.06683232 1.69440176 1.43544276]
  [1.98845931 1.04930461 1.24905542 1.67249346 1.68906229]]

 [[1.86428527 1.56652319 1.7398499  1.06397734 1.57773291]
  [1.96060752 1.86905277 1.12083262 1.80734617 1.92755942]
  [1.76268678 1.20845626 1.03244946 1.02401333 1.73319135]]]


1.9884593091369247
1.0240133277471508
1.5383446542882067


Maximum value of d is 1.9884593091369247, minimum values is 1.0240133277471508, and mean of d is 1.5383446542882067.


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f=np.empty((2,3,5))
print(f)

[[[1.24436632 1.4110992  1.9554217  1.09901926 1.4877428 ]
  [1.89100815 1.958066   1.06683232 1.69440176 1.43544276]
  [1.98845931 1.04930461 1.24905542 1.67249346 1.68906229]]

 [[1.86428527 1.56652319 1.7398499  1.06397734 1.57773291]
  [1.96060752 1.86905277 1.12083262 1.80734617 1.92755942]
  [1.76268678 1.20845626 1.03244946 1.02401333 1.73319135]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

#f is empty array , d is sum of a+c(ones)

# value > d_min and value < d_mean then = 25
# value > d_min and value < d_max then = 75
# value == d_mean then = 50
# value == d_min then = 0
# value == d_max then = 100

print(d)
print(np.shape(d))
print("\n"*3)   

print(d_max)
print(d_min)
print(d_mean)

print("\n"*3)

for i in range(0,len(d)):
    for j in range(0,len(d[i])):
        for k in range(0,len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                q = 25
                f[i][j][k] = np.array(q)
            elif d[i][j][k] > d_min and d[i][j][k] < d_max:
                q = 75
                f[i][j][k] = np.array(q)
            elif d[i][j][k] == d_mean:
                q = 50
                f[i][j][k] = np.array(q)
            elif d[i][j][k] == d_min:
                q = 0
                f[i][j][k] = np.array(q)
            elif d[i][j][k] == d_max:
                q = 100
                f[i][j][k] = np.array(q)

print(f)
print(np.shape(f))

[[[1.24436632 1.4110992  1.9554217  1.09901926 1.4877428 ]
  [1.89100815 1.958066   1.06683232 1.69440176 1.43544276]
  [1.98845931 1.04930461 1.24905542 1.67249346 1.68906229]]

 [[1.86428527 1.56652319 1.7398499  1.06397734 1.57773291]
  [1.96060752 1.86905277 1.12083262 1.80734617 1.92755942]
  [1.76268678 1.20845626 1.03244946 1.02401333 1.73319135]]]
(2, 3, 5)




1.9884593091369247
1.0240133277471508
1.5383446542882067




[[[ 25.  25.  75.  25.  25.]
  [ 75.  75.  25.  75.  25.]
  [100.  25.  25.  75.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25.  25.   0.  75.]]]
(2, 3, 5)



#### 17. Print d and f. Do you have your expected f?
For instance, if your d is:

[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
Your f should be:

[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]

In [19]:
# your code here
print(d)
print(f)

#Yes I believe.. I randomly checked few elements from 'f' for instance 0, 100 etc - all looks matched.

[[[1.24436632 1.4110992  1.9554217  1.09901926 1.4877428 ]
  [1.89100815 1.958066   1.06683232 1.69440176 1.43544276]
  [1.98845931 1.04930461 1.24905542 1.67249346 1.68906229]]

 [[1.86428527 1.56652319 1.7398499  1.06397734 1.57773291]
  [1.96060752 1.86905277 1.12083262 1.80734617 1.92755942]
  [1.76268678 1.20845626 1.03244946 1.02401333 1.73319135]]]
[[[ 25.  25.  75.  25.  25.]
  [ 75.  75.  25.  75.  25.]
  [100.  25.  25.  75.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25.  25.   0.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here

# 0=A, 25=B, 50=C, 75=D, and 100=E

import sys

f=np.empty((2,3,5),dtype="S")

for i in range(0,len(d)):
    for j in range(0,len(d[i])):
        for k in range(0,len(d[i][j])):
            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
                #q = 25
                f[i][j][k] = np.array("A")
            elif d[i][j][k] > d_min and d[i][j][k] < d_max:
                #q = 75
                f[i][j][k] = np.array("D")
            elif d[i][j][k] == d_mean:
                #q = 50
                f[i][j][k] = np.array("C")
            elif d[i][j][k] == d_min:
                #q = 0
                f[i][j][k] = np.array("A")
            elif d[i][j][k] == d_max:
                #q = 100
                f[i][j][k] = np.array("E")

#print(f)
f = f.astype(str)
print(f)
print(np.shape(f))

[[['A' 'A' 'D' 'A' 'A']
  ['D' 'D' 'A' 'D' 'A']
  ['E' 'A' 'A' 'D' 'D']]

 [['D' 'D' 'D' 'A' 'D']
  ['D' 'D' 'A' 'D' 'D']
  ['D' 'A' 'A' 'A' 'D']]]
(2, 3, 5)
