# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here

import numpy as np
import random

#### 2. Print your NumPy version.

In [2]:
# your code here

np.version.version

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1

a = np.random.random((2,3,5))
print(a)

[[[0.26071001 0.0565988  0.61181708 0.26866471 0.80057868]
  [0.64176515 0.99873715 0.06444216 0.25042662 0.13018829]
  [0.82877381 0.67463908 0.04265412 0.96330447 0.50358125]]

 [[0.45959831 0.57593766 0.92259343 0.97956218 0.52279019]
  [0.43979276 0.77653732 0.16511819 0.49614865 0.58375375]
  [0.25403315 0.83665798 0.94990005 0.76820866 0.24276049]]]


In [4]:
# Method 2
t = np.random.rand(2,3,5)
print(t)

[[[0.52541886 0.69110656 0.39857515 0.29605324 0.64283704]
  [0.84572906 0.58107954 0.72493624 0.27116442 0.2715931 ]
  [0.44480196 0.97059632 0.19333939 0.77753758 0.24534618]]

 [[0.75330346 0.64918905 0.42658784 0.1965374  0.03458222]
  [0.18683263 0.27834146 0.45868674 0.79598503 0.52695196]
  [0.70335255 0.14458487 0.01529163 0.09504639 0.90666669]]]


In [5]:
# Method 3
u = np.random.choice(range(0,10000), size=(2,3,5))
print(u)
o = np.random.randint(1000, size=(2,3,5))
print(o)

[[[9744 8897  864 6942 1602]
  [6051 9342 8489 7908 2392]
  [3481 6732 3779 6026 8216]]

 [[7371 2861 9172 2670 9333]
  [5776 4499 1341 6292 9284]
  [6636 1844 4517 3530 4895]]]
[[[ 15 562 898 267 497]
  [805 918 302 711 519]
  [928 877 296 289 382]]

 [[525 879 219 183   6]
  [201 430 249 672 574]
  [429 702 496 716 116]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.26071001 0.0565988  0.61181708 0.26866471 0.80057868]
  [0.64176515 0.99873715 0.06444216 0.25042662 0.13018829]
  [0.82877381 0.67463908 0.04265412 0.96330447 0.50358125]]

 [[0.45959831 0.57593766 0.92259343 0.97956218 0.52279019]
  [0.43979276 0.77653732 0.16511819 0.49614865 0.58375375]
  [0.25403315 0.83665798 0.94990005 0.76820866 0.24276049]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(np.size(a))
print(np.size(b))

bool(np.size(a)==np.size(b))

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

#Let's check their shapes for that first;


print(np.shape(a))
print(np.shape(b))

#Since shapes are different we can not add a and b to each other.
#Let's try..

#c = a + b #nope..

(2, 3, 5)
(5, 2, 3)


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
print(np.shape(a))
print(np.shape(b))
c = np.transpose(b,(1,2,0))   #initial bshape=(5,2,3) so b=(5 (0th element),2 (1st element),3 (2nd element)) -->(b,(1,2,0))
print(np.shape(c))

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
#d=a+c
d=np.add(a,c)

#Shapes are same, so we can do math operations between two arrays.

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here

print(a)
print("\n"*2)
print(d)

#1 is added over values in array a. (or vice versa - values in a is added to ones.array.)

[[[0.26071001 0.0565988  0.61181708 0.26866471 0.80057868]
  [0.64176515 0.99873715 0.06444216 0.25042662 0.13018829]
  [0.82877381 0.67463908 0.04265412 0.96330447 0.50358125]]

 [[0.45959831 0.57593766 0.92259343 0.97956218 0.52279019]
  [0.43979276 0.77653732 0.16511819 0.49614865 0.58375375]
  [0.25403315 0.83665798 0.94990005 0.76820866 0.24276049]]]



[[[1.26071001 1.0565988  1.61181708 1.26866471 1.80057868]
  [1.64176515 1.99873715 1.06444216 1.25042662 1.13018829]
  [1.82877381 1.67463908 1.04265412 1.96330447 1.50358125]]

 [[1.45959831 1.57593766 1.92259343 1.97956218 1.52279019]
  [1.43979276 1.77653732 1.16511819 1.49614865 1.58375375]
  [1.25403315 1.83665798 1.94990005 1.76820866 1.24276049]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here

#e = a * c

e=np.multiply(a,c)
print(e)

[[[0.26071001 0.0565988  0.61181708 0.26866471 0.80057868]
  [0.64176515 0.99873715 0.06444216 0.25042662 0.13018829]
  [0.82877381 0.67463908 0.04265412 0.96330447 0.50358125]]

 [[0.45959831 0.57593766 0.92259343 0.97956218 0.52279019]
  [0.43979276 0.77653732 0.16511819 0.49614865 0.58375375]
  [0.25403315 0.83665798 0.94990005 0.76820866 0.24276049]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
print(a)
print('\n'*2)
print(e)

np.array_equal(a,e)

[[[0.26071001 0.0565988  0.61181708 0.26866471 0.80057868]
  [0.64176515 0.99873715 0.06444216 0.25042662 0.13018829]
  [0.82877381 0.67463908 0.04265412 0.96330447 0.50358125]]

 [[0.45959831 0.57593766 0.92259343 0.97956218 0.52279019]
  [0.43979276 0.77653732 0.16511819 0.49614865 0.58375375]
  [0.25403315 0.83665798 0.94990005 0.76820866 0.24276049]]]



[[[0.26071001 0.0565988  0.61181708 0.26866471 0.80057868]
  [0.64176515 0.99873715 0.06444216 0.25042662 0.13018829]
  [0.82877381 0.67463908 0.04265412 0.96330447 0.50358125]]

 [[0.45959831 0.57593766 0.92259343 0.97956218 0.52279019]
  [0.43979276 0.77653732 0.16511819 0.49614865 0.58375375]
  [0.25403315 0.83665798 0.94990005 0.76820866 0.24276049]]]


True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
print(d)

d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("\n")

print(d_max)
print(d_min)
print(d_mean)

print("\n")
print(f"Maximum value of d is {d_max}, minimum values is {d_min}, and mean of d is {d_mean}.")

[[[1.26071001 1.0565988  1.61181708 1.26866471 1.80057868]
  [1.64176515 1.99873715 1.06444216 1.25042662 1.13018829]
  [1.82877381 1.67463908 1.04265412 1.96330447 1.50358125]]

 [[1.45959831 1.57593766 1.92259343 1.97956218 1.52279019]
  [1.43979276 1.77653732 1.16511819 1.49614865 1.58375375]
  [1.25403315 1.83665798 1.94990005 1.76820866 1.24276049]]]


1.9987371470326714
1.0426541241515137
1.5356758059729605


Maximum value of d is 1.9987371470326714, minimum values is 1.0426541241515137, and mean of d is 1.5356758059729605.


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f=np.empty((2,3,5))
print(f)

[[[1.26071001 1.0565988  1.61181708 1.26866471 1.80057868]
  [1.64176515 1.99873715 1.06444216 1.25042662 1.13018829]
  [1.82877381 1.67463908 1.04265412 1.96330447 1.50358125]]

 [[1.45959831 1.57593766 1.92259343 1.97956218 1.52279019]
  [1.43979276 1.77653732 1.16511819 1.49614865 1.58375375]
  [1.25403315 1.83665798 1.94990005 1.76820866 1.24276049]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here

#f is empty array , d is sum of a+c(ones)

# value > d_min and value < d_mean then = 25
# value > d_mean and value < d_max then = 75
# value == d_mean then = 50
# value == d_min then = 0
# value == d_max then = 100

print(d)
print(np.shape(d))
print("\n"*3)   

print(d_max)
print(d_min)
print(d_mean)

print("\n"*3)

#for i in range(0,len(d)):
#    for j in range(0,len(d[i])):
#        for k in range(0,len(d[i][j])):
#            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
#                q = 25
#                f[i][j][k] = np.array(q)
#            elif d[i][j][k] > d_min and d[i][j][k] < d_max:
#                q = 75
#                f[i][j][k] = np.array(q)
#            elif d[i][j][k] == d_mean:
#                q = 50
#                f[i][j][k] = np.array(q)
#            elif d[i][j][k] == d_min:
#                q = 0
#                f[i][j][k] = np.array(q)
#            elif d[i][j][k] == d_max:
#                q = 100
#                f[i][j][k] = np.array(q)

#print(f)
#print(np.shape(f))

#----------------------------------- after REVIEW -----------------------

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d  < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

f



[[[1.26071001 1.0565988  1.61181708 1.26866471 1.80057868]
  [1.64176515 1.99873715 1.06444216 1.25042662 1.13018829]
  [1.82877381 1.67463908 1.04265412 1.96330447 1.50358125]]

 [[1.45959831 1.57593766 1.92259343 1.97956218 1.52279019]
  [1.43979276 1.77653732 1.16511819 1.49614865 1.58375375]
  [1.25403315 1.83665798 1.94990005 1.76820866 1.24276049]]]
(2, 3, 5)




1.9987371470326714
1.0426541241515137
1.5356758059729605






array([[[ 25.,  25.,  75.,  25.,  75.],
        [ 75., 100.,  25.,  25.,  25.],
        [ 75.,  75.,   0.,  75.,  25.]],

       [[ 25.,  75.,  75.,  75.,  25.],
        [ 25.,  75.,  25.,  25.,  75.],
        [ 25.,  75.,  75.,  75.,  25.]]])


#### 17. Print d and f. Do you have your expected f?
For instance, if your d is:

[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
Your f should be:

[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]

In [19]:
# your code here
print(d)
print(f)

#Yes I believe.. I randomly checked few elements from 'f' for instance 0, 100 etc - all looks matched.

[[[1.26071001 1.0565988  1.61181708 1.26866471 1.80057868]
  [1.64176515 1.99873715 1.06444216 1.25042662 1.13018829]
  [1.82877381 1.67463908 1.04265412 1.96330447 1.50358125]]

 [[1.45959831 1.57593766 1.92259343 1.97956218 1.52279019]
  [1.43979276 1.77653732 1.16511819 1.49614865 1.58375375]
  [1.25403315 1.83665798 1.94990005 1.76820866 1.24276049]]]
[[[ 25.  25.  75.  25.  75.]
  [ 75. 100.  25.  25.  25.]
  [ 75.  75.   0.  75.  25.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here

# 0=A, 25=B, 50=C, 75=D, and 100=E

#import sys

#f=np.empty((2,3,5),dtype="S")

#for i in range(0,len(d)):
#    for j in range(0,len(d[i])):
#        for k in range(0,len(d[i][j])):
#            if d[i][j][k] > d_min and d[i][j][k] < d_mean:
#                #q = 25
#                f[i][j][k] = np.array("A")
#            elif d[i][j][k] > d_min and d[i][j][k] < d_max:
#                #q = 75
#                f[i][j][k] = np.array("D")
#            elif d[i][j][k] == d_mean:
#                #q = 50
#                f[i][j][k] = np.array("C")
#            elif d[i][j][k] == d_min:
#                #q = 0
#                f[i][j][k] = np.array("A")
#            elif d[i][j][k] == d_max:
#                #q = 100
#                f[i][j][k] = np.array("E")

#print(f)
#f = f.astype(str)
#print(f)
#print(np.shape(f))

#----------------------------------- after REVIEW -----------------------

f=np.empty((2,3,5),dtype="str")
f[(d > d_min) & (d < d_mean)] = "B"
f[(d > d_mean) & (d  < d_max)] = "D"
f[d == d_mean] = "C"
f[d == d_min] = "A"
f[d == d_max] = "E"

print(f)

[[['B' 'B' 'D' 'B' 'D']
  ['D' 'E' 'B' 'B' 'B']
  ['D' 'D' 'A' 'D' 'B']]

 [['B' 'D' 'D' 'D' 'B']
  ['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'D' 'D' 'B']]]
