# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[8.97324311e-01 3.29976947e-01 8.16552619e-04 2.26159990e-01
   5.70419013e-02]
  [4.73614815e-01 6.04967835e-01 7.03671424e-01 2.14385161e-01
   6.67609734e-01]
  [7.25536961e-01 4.54752517e-01 6.47820997e-01 7.41889345e-01
   7.03097531e-01]]

 [[5.99668231e-01 4.85474922e-01 7.11961996e-01 7.83094147e-01
   6.81436324e-01]
  [9.67466993e-01 6.18063863e-01 5.09215889e-01 1.35741679e-01
   6.97090488e-01]
  [3.81635030e-01 7.84975419e-01 3.56626939e-01 5.60540250e-01
   9.86292355e-01]]]


In [4]:
# Method 2
a = np.arange(30).reshape(2,3,5)
print(a)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [5]:
# Method 3
a = np.random.rand(2, 3, 5)

print(a)

[[[6.57996964e-01 2.57033865e-01 2.36742544e-01 2.20210976e-01
   9.10327542e-01]
  [5.61943191e-01 5.26129530e-01 7.02299659e-02 9.28717684e-01
   3.91094568e-01]
  [3.58404718e-02 3.83508549e-01 8.12665080e-01 4.42087889e-01
   7.07481123e-04]]

 [[1.71796143e-01 4.68578975e-01 5.21663329e-01 2.31107905e-01
   9.72369904e-01]
  [6.11655740e-02 8.95870447e-01 2.67134635e-01 8.74774226e-01
   4.61568221e-01]
  [7.01755597e-01 6.82982748e-01 5.20781238e-01 7.82493263e-01
   2.16661624e-01]]]


#### 4. Print *a*.


In [6]:
# your code here
#done before

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b=np.full((5,2,3), 1)


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size== b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#np.add(a,b)
#cant add as they dont have same shape


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c=b.reshape(2,3,5)
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d=np.add(c,a)
print(d)
#it works because they both have same shape

[[[1.65799696 1.25703387 1.23674254 1.22021098 1.91032754]
  [1.56194319 1.52612953 1.07022997 1.92871768 1.39109457]
  [1.03584047 1.38350855 1.81266508 1.44208789 1.00070748]]

 [[1.17179614 1.46857898 1.52166333 1.23110791 1.9723699 ]
  [1.06116557 1.89587045 1.26713463 1.87477423 1.46156822]
  [1.7017556  1.68298275 1.52078124 1.78249326 1.21666162]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
#it has added 1 to each value

[[[6.57996964e-01 2.57033865e-01 2.36742544e-01 2.20210976e-01
   9.10327542e-01]
  [5.61943191e-01 5.26129530e-01 7.02299659e-02 9.28717684e-01
   3.91094568e-01]
  [3.58404718e-02 3.83508549e-01 8.12665080e-01 4.42087889e-01
   7.07481123e-04]]

 [[1.71796143e-01 4.68578975e-01 5.21663329e-01 2.31107905e-01
   9.72369904e-01]
  [6.11655740e-02 8.95870447e-01 2.67134635e-01 8.74774226e-01
   4.61568221e-01]
  [7.01755597e-01 6.82982748e-01 5.20781238e-01 7.82493263e-01
   2.16661624e-01]]]
[[[1.65799696 1.25703387 1.23674254 1.22021098 1.91032754]
  [1.56194319 1.52612953 1.07022997 1.92871768 1.39109457]
  [1.03584047 1.38350855 1.81266508 1.44208789 1.00070748]]

 [[1.17179614 1.46857898 1.52166333 1.23110791 1.9723699 ]
  [1.06116557 1.89587045 1.26713463 1.87477423 1.46156822]
  [1.7017556  1.68298275 1.52078124 1.78249326 1.21666162]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e=np.multiply(a,c)
print(e)

[[[6.57996964e-01 2.57033865e-01 2.36742544e-01 2.20210976e-01
   9.10327542e-01]
  [5.61943191e-01 5.26129530e-01 7.02299659e-02 9.28717684e-01
   3.91094568e-01]
  [3.58404718e-02 3.83508549e-01 8.12665080e-01 4.42087889e-01
   7.07481123e-04]]

 [[1.71796143e-01 4.68578975e-01 5.21663329e-01 2.31107905e-01
   9.72369904e-01]
  [6.11655740e-02 8.95870447e-01 2.67134635e-01 8.74774226e-01
   4.61568221e-01]
  [7.01755597e-01 6.82982748e-01 5.20781238e-01 7.82493263e-01
   2.16661624e-01]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e==a
#because its mutiplying by 1 .so the result remains same

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_mean=np.mean(d)
print(d_mean)
d_max=np.max(d)
print(d_max)
d_min=np.min(d)
print(d_min)

1.475531337669903
1.9723699035968805
1.0007074811231225


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f=np.empty([2,3,5], dtype=float)
print(f)

[[[6.57996964e-01 2.57033865e-01 2.36742544e-01 2.20210976e-01
   9.10327542e-01]
  [5.61943191e-01 5.26129530e-01 7.02299659e-02 9.28717684e-01
   3.91094568e-01]
  [3.58404718e-02 3.83508549e-01 8.12665080e-01 4.42087889e-01
   7.07481123e-04]]

 [[1.71796143e-01 4.68578975e-01 5.21663329e-01 2.31107905e-01
   9.72369904e-01]
  [6.11655740e-02 8.95870447e-01 2.67134635e-01 8.74774226e-01
   4.61568221e-01]
  [7.01755597e-01 6.82982748e-01 5.20781238e-01 7.82493263e-01
   2.16661624e-01]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100



print(f)

[[[ 75.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  25.   0.]]

 [[ 25.  25.  75.  25. 100.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [19]:
# your code here
print(d)
print("\n")
print(f)

[[[1.65799696 1.25703387 1.23674254 1.22021098 1.91032754]
  [1.56194319 1.52612953 1.07022997 1.92871768 1.39109457]
  [1.03584047 1.38350855 1.81266508 1.44208789 1.00070748]]

 [[1.17179614 1.46857898 1.52166333 1.23110791 1.9723699 ]
  [1.06116557 1.89587045 1.26713463 1.87477423 1.46156822]
  [1.7017556  1.68298275 1.52078124 1.78249326 1.21666162]]]


[[[ 75.  25.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  25.  75.  25.   0.]]

 [[ 25.  25.  75.  25. 100.]
  [ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
[[["A" if x == d_min else "B" if d_min<x<d_mean else "C" if x == d_mean else "D" if d_mean<x<d_max else "E" for x in j] for j in y] for y in d]


[[['D', 'B', 'B', 'B', 'D'],
  ['D', 'D', 'B', 'D', 'B'],
  ['B', 'B', 'D', 'B', 'A']],
 [['B', 'B', 'D', 'B', 'E'],
  ['B', 'D', 'B', 'D', 'B'],
  ['D', 'D', 'D', 'D', 'B']]]