# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.version.version

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.04284922 0.54780325 0.13442421 0.61942629 0.84772385]
  [0.49804363 0.4328248  0.1607563  0.80618454 0.72215276]
  [0.96401236 0.01888298 0.11842822 0.56269986 0.65320595]]

 [[0.66513136 0.26161561 0.32432689 0.60685602 0.58269095]
  [0.79502672 0.75116685 0.92282645 0.30114926 0.52465799]
  [0.59834061 0.30989227 0.83291036 0.30371205 0.34229274]]]


In [4]:
# Method 2
i = np.empty((2,3,5))
print(i)

[[[0.04284922 0.54780325 0.13442421 0.61942629 0.84772385]
  [0.49804363 0.4328248  0.1607563  0.80618454 0.72215276]
  [0.96401236 0.01888298 0.11842822 0.56269986 0.65320595]]

 [[0.66513136 0.26161561 0.32432689 0.60685602 0.58269095]
  [0.79502672 0.75116685 0.92282645 0.30114926 0.52465799]
  [0.59834061 0.30989227 0.83291036 0.30371205 0.34229274]]]


In [5]:
# Method 3
import random
lst = []

for i in range(0,30):
    x = random.random()
    lst.append(x)

g = np.array(lst)

h = g.reshape((2,3,5))
print(h)

[[[0.77462692 0.44472058 0.09247728 0.21213312 0.71228927]
  [0.77166651 0.07406247 0.41841931 0.16922313 0.06899579]
  [0.3155745  0.618323   0.86184652 0.75469282 0.26542833]]

 [[0.19902663 0.24087892 0.62972363 0.01491509 0.10194763]
  [0.91137602 0.02832692 0.82372665 0.67163037 0.0828575 ]
  [0.17393319 0.57009621 0.50637501 0.90916548 0.59591137]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.04284922 0.54780325 0.13442421 0.61942629 0.84772385]
  [0.49804363 0.4328248  0.1607563  0.80618454 0.72215276]
  [0.96401236 0.01888298 0.11842822 0.56269986 0.65320595]]

 [[0.66513136 0.26161561 0.32432689 0.60685602 0.58269095]
  [0.79502672 0.75116685 0.92282645 0.30114926 0.52465799]
  [0.59834061 0.30989227 0.83291036 0.30371205 0.34229274]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size)
print(b.size)

30
30


#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
#Not possible, because they do have the same size, but not the same shape.
#np.add(a,b)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.reshape((2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
print(d)

[[[1.04284922 1.54780325 1.13442421 1.61942629 1.84772385]
  [1.49804363 1.4328248  1.1607563  1.80618454 1.72215276]
  [1.96401236 1.01888298 1.11842822 1.56269986 1.65320595]]

 [[1.66513136 1.26161561 1.32432689 1.60685602 1.58269095]
  [1.79502672 1.75116685 1.92282645 1.30114926 1.52465799]
  [1.59834061 1.30989227 1.83291036 1.30371205 1.34229274]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
# Difference/relation betwee a and d: d contains all the individual values of (a+1)

[[[0.04284922 0.54780325 0.13442421 0.61942629 0.84772385]
  [0.49804363 0.4328248  0.1607563  0.80618454 0.72215276]
  [0.96401236 0.01888298 0.11842822 0.56269986 0.65320595]]

 [[0.66513136 0.26161561 0.32432689 0.60685602 0.58269095]
  [0.79502672 0.75116685 0.92282645 0.30114926 0.52465799]
  [0.59834061 0.30989227 0.83291036 0.30371205 0.34229274]]]
[[[1.04284922 1.54780325 1.13442421 1.61942629 1.84772385]
  [1.49804363 1.4328248  1.1607563  1.80618454 1.72215276]
  [1.96401236 1.01888298 1.11842822 1.56269986 1.65320595]]

 [[1.66513136 1.26161561 1.32432689 1.60685602 1.58269095]
  [1.79502672 1.75116685 1.92282645 1.30114926 1.52465799]
  [1.59834061 1.30989227 1.83291036 1.30371205 1.34229274]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.04284922 0.54780325 0.13442421 0.61942629 0.84772385]
  [0.49804363 0.4328248  0.1607563  0.80618454 0.72215276]
  [0.96401236 0.01888298 0.11842822 0.56269986 0.65320595]]

 [[0.66513136 0.26161561 0.32432689 0.60685602 0.58269095]
  [0.79502672 0.75116685 0.92282645 0.30114926 0.52465799]
  [0.59834061 0.30989227 0.83291036 0.30371205 0.34229274]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
#e equals a, because e = individual values of a multiplied by 1.

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [40]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max)
print(d_min)
print(d_mean)

1.9640123585283233
1.0188829754448951
1.5084004779728701


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [21]:
# your code here
f = np.empty((2,3,5))

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [38]:
# your code here
lst = []

for x in d:
    for y in x:
        for z in y:
            if z > d_min and z < d_mean:
                lst.append(25)
            elif z > d_mean and z < d_max:
                lst.append(75)
            elif z == d_mean:
                lst.append(50)
            elif z == d_min:
                lst.append(0)
            elif z == d_max:
                lst.append(100)
            else:
                lst.append(999)

arr = np.array(lst)

f = np.reshape(arr,(2,3,5))
print(f)

[[[ 25  75  25  75  75]
  [ 25  25  25  75  75]
  [100   0  25  75  75]]

 [[ 75  25  25  75  75]
  [ 75  75  75  25  75]
  [ 75  25  75  25  25]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [39]:
# your code here
print(d)
print(f)

[[[1.04284922 1.54780325 1.13442421 1.61942629 1.84772385]
  [1.49804363 1.4328248  1.1607563  1.80618454 1.72215276]
  [1.96401236 1.01888298 1.11842822 1.56269986 1.65320595]]

 [[1.66513136 1.26161561 1.32432689 1.60685602 1.58269095]
  [1.79502672 1.75116685 1.92282645 1.30114926 1.52465799]
  [1.59834061 1.30989227 1.83291036 1.30371205 1.34229274]]]
[[[ 25  75  25  75  75]
  [ 25  25  25  75  75]
  [100   0  25  75  75]]

 [[ 75  25  25  75  75]
  [ 75  75  75  25  75]
  [ 75  25  75  25  25]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [50]:
# your code here
fnew = np.where(f==0, 'A', fnew)
fnew = np.where(f==25, 'B', fnew)
fnew = np.where(f==50, 'C', fnew)
fnew = np.where(f==75, 'D', fnew)
fnew = np.where(f==100, 'E', fnew)
print(fnew)

[[['B' 'D' 'B' 'D' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['E' 'A' 'B' 'D' 'D']]

 [['D' 'B' 'B' 'D' 'D']
  ['D' 'D' 'D' 'B' 'D']
  ['D' 'B' 'D' 'B' 'B']]]
