# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.version.version)

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random(30).reshape(2,3,5)
a

In [4]:
# Method 2
a = np.random.random((2,3,5))


In [5]:
# Method 3
a = np.random.random_sample(30).reshape(2,3,5)
a

#### 4. Print *a*.


In [6]:
# your code here
print(a)

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here
try:
    np.add(a,b)
except ValueError:
    print('They need to have the same shapes')
#They need to have the same shapes

They need to have the same shapes


#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
np.add(a,c)
# because they have the same shape
d = np.add(a,c)#.sum()
d

array([[[1.63322514, 1.48836836, 1.35571244, 1.2409279 , 1.70021238],
        [1.13505184, 1.37461618, 1.10905893, 1.87170333, 1.31646674],
        [1.10349934, 1.50949712, 1.06280867, 1.2398718 , 1.24171552]],

       [[1.15283497, 1.11352834, 1.92094743, 1.87495159, 1.2430079 ],
        [1.51748541, 1.68423584, 1.31707513, 1.19789569, 1.14140752],
        [1.19731857, 1.96982542, 1.53541915, 1.59910763, 1.85110684]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a,d)


[[[0.63322514 0.48836836 0.35571244 0.2409279  0.70021238]
  [0.13505184 0.37461618 0.10905893 0.87170333 0.31646674]
  [0.10349934 0.50949712 0.06280867 0.2398718  0.24171552]]

 [[0.15283497 0.11352834 0.92094743 0.87495159 0.2430079 ]
  [0.51748541 0.68423584 0.31707513 0.19789569 0.14140752]
  [0.19731857 0.96982542 0.53541915 0.59910763 0.85110684]]] [[[1.63322514 1.48836836 1.35571244 1.2409279  1.70021238]
  [1.13505184 1.37461618 1.10905893 1.87170333 1.31646674]
  [1.10349934 1.50949712 1.06280867 1.2398718  1.24171552]]

 [[1.15283497 1.11352834 1.92094743 1.87495159 1.2430079 ]
  [1.51748541 1.68423584 1.31707513 1.19789569 1.14140752]
  [1.19731857 1.96982542 1.53541915 1.59910763 1.85110684]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)
e

array([[[0.63322514, 0.48836836, 0.35571244, 0.2409279 , 0.70021238],
        [0.13505184, 0.37461618, 0.10905893, 0.87170333, 0.31646674],
        [0.10349934, 0.50949712, 0.06280867, 0.2398718 , 0.24171552]],

       [[0.15283497, 0.11352834, 0.92094743, 0.87495159, 0.2430079 ],
        [0.51748541, 0.68423584, 0.31707513, 0.19789569, 0.14140752],
        [0.19731857, 0.96982542, 0.53541915, 0.59910763, 0.85110684]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
a.all() == e.all()
    
#because 0.6 == (0.6*1)

True

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max,d_min,d_mean)

1.9698254198893734 1.0628086698803196 1.423296103275477


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2,3,5])
f

array([[[0.63322514, 0.48836836, 0.35571244, 0.2409279 , 0.70021238],
        [0.13505184, 0.37461618, 0.10905893, 0.87170333, 0.31646674],
        [0.10349934, 0.50949712, 0.06280867, 0.2398718 , 0.24171552]],

       [[0.15283497, 0.11352834, 0.92094743, 0.87495159, 0.2430079 ],
        [0.51748541, 0.68423584, 0.31707513, 0.19789569, 0.14140752],
        [0.19731857, 0.96982542, 0.53541915, 0.59910763, 0.85110684]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
f = [[[0 if x == d_min else 25 if d_min<x<d_mean else 50 if x == d_mean else 75 if d_mean<x<d_max else 100 for x in j] for j in y] for y in d]

In [19]:
f = 0 * (d == d_min) + 25 * (d > d_min) * (d < d_mean) + 50 * (d == d_mean) + 75 * (d < d_max) * (d > d_mean) + 100 * (d == d_max) 

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
[[["A" if x == d_min else "B" if d_min<x<d_mean else "C" if x == d_mean else "D" if d_mean<x<d_max else "E" for x in j] for j in y] for y in d]

[[['D', 'D', 'B', 'B', 'D'],
  ['B', 'B', 'B', 'D', 'B'],
  ['B', 'D', 'A', 'B', 'B']],
 [['B', 'B', 'D', 'D', 'B'],
  ['D', 'D', 'B', 'B', 'B'],
  ['B', 'E', 'D', 'D', 'D']]]