# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.19.0


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
a = np.empty((2,3,5))

In [5]:
# Method 3
a = np.arange(30).reshape(2,3,5)

#### 4. Print *a*.


In [6]:
# your code here
a = np.random.random((2,3,5))
print(a)


[[[0.27971552 0.5978824  0.02008202 0.98092308 0.01173458]
  [0.52847578 0.60292577 0.48484444 0.21755564 0.96536258]
  [0.39280633 0.25064057 0.14199658 0.56786427 0.14236394]]

 [[0.46606688 0.43871839 0.80274094 0.43441646 0.86781886]
  [0.35939611 0.27661197 0.0106704  0.48942558 0.44613736]
  [0.84632521 0.17468636 0.99246705 0.23394334 0.48202968]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [7]:
# your code here
b = np.ones((5,2,3))


#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
print(a.size)
print(b.size)
a.size == b.size

30
30


True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [10]:
# your answer here

# Though of same size, a and b cannot be added since they are of different dimensions.
#sum = np.add(a,b)
#print(sum)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [11]:
# your code here
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [12]:
# your code/answer here
d = np.add(a,c)
print(d)

[[[1.27971552 1.5978824  1.02008202 1.98092308 1.01173458]
  [1.52847578 1.60292577 1.48484444 1.21755564 1.96536258]
  [1.39280633 1.25064057 1.14199658 1.56786427 1.14236394]]

 [[1.46606688 1.43871839 1.80274094 1.43441646 1.86781886]
  [1.35939611 1.27661197 1.0106704  1.48942558 1.44613736]
  [1.84632521 1.17468636 1.99246705 1.23394334 1.48202968]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
# your code/answer here
print(a)
print(d)
#Adding 1 to each element in array "a" gives array "d"

[[[0.27971552 0.5978824  0.02008202 0.98092308 0.01173458]
  [0.52847578 0.60292577 0.48484444 0.21755564 0.96536258]
  [0.39280633 0.25064057 0.14199658 0.56786427 0.14236394]]

 [[0.46606688 0.43871839 0.80274094 0.43441646 0.86781886]
  [0.35939611 0.27661197 0.0106704  0.48942558 0.44613736]
  [0.84632521 0.17468636 0.99246705 0.23394334 0.48202968]]]
[[[1.27971552 1.5978824  1.02008202 1.98092308 1.01173458]
  [1.52847578 1.60292577 1.48484444 1.21755564 1.96536258]
  [1.39280633 1.25064057 1.14199658 1.56786427 1.14236394]]

 [[1.46606688 1.43871839 1.80274094 1.43441646 1.86781886]
  [1.35939611 1.27661197 1.0106704  1.48942558 1.44613736]
  [1.84632521 1.17468636 1.99246705 1.23394334 1.48202968]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [14]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.27971552 0.5978824  0.02008202 0.98092308 0.01173458]
  [0.52847578 0.60292577 0.48484444 0.21755564 0.96536258]
  [0.39280633 0.25064057 0.14199658 0.56786427 0.14236394]]

 [[0.46606688 0.43871839 0.80274094 0.43441646 0.86781886]
  [0.35939611 0.27661197 0.0106704  0.48942558 0.44613736]
  [0.84632521 0.17468636 0.99246705 0.23394334 0.48202968]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [15]:
# your code/answer here
e == a
#because it just gets multiplied by 1 the answer remains the same.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [16]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9924670453875049
1.0106703980400915
1.4502209364163008


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [17]:
# your code here
f = np.empty([2,3,5])
print(f)

[[[0.27971552 0.5978824  0.02008202 0.98092308 0.01173458]
  [0.52847578 0.60292577 0.48484444 0.21755564 0.96536258]
  [0.39280633 0.25064057 0.14199658 0.56786427 0.14236394]]

 [[0.46606688 0.43871839 0.80274094 0.43441646 0.86781886]
  [0.35939611 0.27661197 0.0106704  0.48942558 0.44613736]
  [0.84632521 0.17468636 0.99246705 0.23394334 0.48202968]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [18]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100
print(f)

[[[ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  25.   0.  75.  25.]
  [ 75.  25. 100.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [22]:
# your code here
print(d)
print(f)

[[[1.27971552 1.5978824  1.02008202 1.98092308 1.01173458]
  [1.52847578 1.60292577 1.48484444 1.21755564 1.96536258]
  [1.39280633 1.25064057 1.14199658 1.56786427 1.14236394]]

 [[1.46606688 1.43871839 1.80274094 1.43441646 1.86781886]
  [1.35939611 1.27661197 1.0106704  1.48942558 1.44613736]
  [1.84632521 1.17468636 1.99246705 1.23394334 1.48202968]]]
[[[ 25.  75.  25.  75.  25.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  25.  75.  25.  75.]
  [ 25.  25.   0.  75.  25.]
  [ 75.  25. 100.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [20]:
# your code here
