# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print (np)

<module 'numpy' from 'C:\\Users\\Merti\\Anaconda3\\lib\\site-packages\\numpy\\__init__.py'>


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5)) # np.zeros will give you 0s, np.ones will give you 1s
#this random will only give you numbers between 0 and 1

In [29]:
# Method 2
rand_a = np.random.randn(2,3,5)
print(rand_a)

[[[ 0.69791658  0.95934881  0.23071453 -2.10727106  0.31974295]
  [ 0.70688387  0.56830844  0.64053565  0.82450676  0.10302561]
  [ 0.30143554  0.55662775 -1.42786679  0.56978732  0.95577023]]

 [[ 0.50084418 -0.93770284  0.12689047 -1.22743303  0.23568788]
  [ 1.07282784 -0.67954317  0.37260258  1.45678434 -0.82350888]
  [-0.91092321  1.07434146  0.56226157 -2.23169096  0.78948307]]]


In [31]:
# Method 3
rand_a1 = np.random.rand(2,3,5)
print(rand_a1)

[[[0.68546926 0.0820238  0.77416211 0.27828909 0.34569036]
  [0.28235604 0.00303868 0.72378926 0.07716915 0.73085059]
  [0.12775179 0.59597288 0.75688772 0.53271567 0.47275032]]

 [[0.1591286  0.34327121 0.43929943 0.70422296 0.35650981]
  [0.73776509 0.43897146 0.16480092 0.70693939 0.75783379]
  [0.92564008 0.51489706 0.71061183 0.19138139 0.18380132]]]


#### 4. Print *a*.


In [6]:
# your code here
print(a)

[[[0.97703967 0.79049033 0.02767464 0.67163448 0.70448237]
  [0.04479265 0.81176802 0.20224035 0.54407648 0.68717548]
  [0.1711127  0.65799968 0.78258986 0.69728027 0.19180627]]

 [[0.0547179  0.52173547 0.89666159 0.41511122 0.33272049]
  [0.35023138 0.80230038 0.95329923 0.46861657 0.42531117]
  [0.04576752 0.85908437 0.45145913 0.50195805 0.78872959]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [27]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [8]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [9]:
# your code here
a.size

30

In [10]:
b.size

30

In [11]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [12]:
# your answer here #no there is an error since the arrays do not have the same shape
print(a+b)


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
np.add(a,b)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [13]:
# your code here
c = np.reshape(b,(2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [14]:
# your code/answer here
d = np.add(a,c) #it works because the arrays are the same shape
print(d)

[[[1.97703967 1.79049033 1.02767464 1.67163448 1.70448237]
  [1.04479265 1.81176802 1.20224035 1.54407648 1.68717548]
  [1.1711127  1.65799968 1.78258986 1.69728027 1.19180627]]

 [[1.0547179  1.52173547 1.89666159 1.41511122 1.33272049]
  [1.35023138 1.80230038 1.95329923 1.46861657 1.42531117]
  [1.04576752 1.85908437 1.45145913 1.50195805 1.78872959]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [15]:
# your code/answer here
print(a) 

[[[0.97703967 0.79049033 0.02767464 0.67163448 0.70448237]
  [0.04479265 0.81176802 0.20224035 0.54407648 0.68717548]
  [0.1711127  0.65799968 0.78258986 0.69728027 0.19180627]]

 [[0.0547179  0.52173547 0.89666159 0.41511122 0.33272049]
  [0.35023138 0.80230038 0.95329923 0.46861657 0.42531117]
  [0.04576752 0.85908437 0.45145913 0.50195805 0.78872959]]]


In [16]:
print(d) #d is the array a plus 1 added to each value

[[[1.97703967 1.79049033 1.02767464 1.67163448 1.70448237]
  [1.04479265 1.81176802 1.20224035 1.54407648 1.68717548]
  [1.1711127  1.65799968 1.78258986 1.69728027 1.19180627]]

 [[1.0547179  1.52173547 1.89666159 1.41511122 1.33272049]
  [1.35023138 1.80230038 1.95329923 1.46861657 1.42531117]
  [1.04576752 1.85908437 1.45145913 1.50195805 1.78872959]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [17]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.97703967 0.79049033 0.02767464 0.67163448 0.70448237]
  [0.04479265 0.81176802 0.20224035 0.54407648 0.68717548]
  [0.1711127  0.65799968 0.78258986 0.69728027 0.19180627]]

 [[0.0547179  0.52173547 0.89666159 0.41511122 0.33272049]
  [0.35023138 0.80230038 0.95329923 0.46861657 0.42531117]
  [0.04576752 0.85908437 0.45145913 0.50195805 0.78872959]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [18]:
# your code/answer here
a == e #yes they are equal because c is just values of 1 so multiplying elements in a by 1 just gives the same elements

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [19]:
# your code here
d_mean = np.mean(d)
print(d_mean)

1.5276622439283967


In [20]:
d_max = np.max(d)
print(d_max)

1.9770396689355876


In [21]:
d_min = np.min(d)
print(d_min)

1.0276746433082602


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [22]:
f = np.empty((2,3,5))
print(f)

[[[0.97703967 0.79049033 0.02767464 0.67163448 0.70448237]
  [0.04479265 0.81176802 0.20224035 0.54407648 0.68717548]
  [0.1711127  0.65799968 0.78258986 0.69728027 0.19180627]]

 [[0.0547179  0.52173547 0.89666159 0.41511122 0.33272049]
  [0.35023138 0.80230038 0.95329923 0.46861657 0.42531117]
  [0.04576752 0.85908437 0.45145913 0.50195805 0.78872959]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [ ]:

#none of these work
#for x in range(0,3):
    #if d_min < x < d_mean:
        #f.append(25)
    #elif d_mean < x < d_max:
     #   f.append(75)
    #elif x == d_mean:
     #   f.append(50)
    #elif x == d_min:
     #   f.append(0)
    #elif x == d_max:
     #   f.append(100)
#print(f)


#for x in d:
   # print(np.where(d_min < x < d_mean, a.all(), 25))
    
#d = np.add(a,c)
#for x in d:
 #   print(np.where(x==d.mean, a, 50))
#for x in d:
  #  for y in x:
   #     for z in y:
    #        if d_min < z < d_mean:
    #            z=25
     #           f.append(z)
#print(f)
#solution from https://stackoverflow.com/questions/50077712/replacing-2d-subarray-in-3d-array-if-condition-is-met/50078478#50078478

In [23]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)

[[[100.  75.   0.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  75.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [24]:
# your code here
print(d)

[[[1.97703967 1.79049033 1.02767464 1.67163448 1.70448237]
  [1.04479265 1.81176802 1.20224035 1.54407648 1.68717548]
  [1.1711127  1.65799968 1.78258986 1.69728027 1.19180627]]

 [[1.0547179  1.52173547 1.89666159 1.41511122 1.33272049]
  [1.35023138 1.80230038 1.95329923 1.46861657 1.42531117]
  [1.04576752 1.85908437 1.45145913 1.50195805 1.78872959]]]


In [25]:
print(f)

[[[100.  75.   0.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  75.  75.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [26]:
# your code here
f = np.array(f, dtype = 'object')
f[(d > d_min) & (d < d_mean)] = "B"
f[(d > d_mean) & (d < d_max)] = "D"
f[d == d_mean] = "C"
f[d == d_min] = "A"
f[d == d_max] = "E"

print(f)

[[['E' 'D' 'A' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['B' 'D' 'D' 'D' 'B']]

 [['B' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'B']
  ['B' 'D' 'B' 'B' 'D']]]
