# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [19]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [20]:
# your code here
print(np.__version__)

1.17.2


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [202]:
# Method 1
a = np.random.random((2,3,5))
print(a)

[[[0.45288089 0.54379744 0.18695451 0.23672633 0.97246315]
  [0.35550187 0.62060939 0.19439752 0.77227066 0.17164491]
  [0.35871008 0.46075427 0.0244904  0.63971789 0.34212579]]

 [[0.66637854 0.02685716 0.24518018 0.75365265 0.19340251]
  [0.22293207 0.35146459 0.5187191  0.09592204 0.53307647]
  [0.72666629 0.19312147 0.76590511 0.26275256 0.0183864 ]]]


In [214]:
# Method 2
a = np.random.randint(1000, size = (2, 3, 5))
print(a)

TypeError: randint() got an unexpected keyword argument 'size'

In [215]:
# Method 3

a_1 = np.random.choice((100), size = (2, 3, 5))
print(a)

[[[0.45288089 0.54379744 0.18695451 0.23672633 0.97246315]
  [0.35550187 0.62060939 0.19439752 0.77227066 0.17164491]
  [0.35871008 0.46075427 0.0244904  0.63971789 0.34212579]]

 [[0.66637854 0.02685716 0.24518018 0.75365265 0.19340251]
  [0.22293207 0.35146459 0.5187191  0.09592204 0.53307647]
  [0.72666629 0.19312147 0.76590511 0.26275256 0.0183864 ]]]


#### 4. Print *a*.


In [122]:
# your code here
print(a)

[[[0.40783714 0.44345756 0.21116334 0.9762221  0.00441201]
  [0.01370557 0.8865732  0.26721333 0.67917855 0.31589216]
  [0.61010002 0.67181993 0.78667661 0.33437508 0.30892157]]

 [[0.34833691 0.91319453 0.44508212 0.33491205 0.78133097]
  [0.19541215 0.45680016 0.63444324 0.60813922 0.47043436]
  [0.08775172 0.14291936 0.8203082  0.87756593 0.65593696]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [123]:
# your code here
b = np.random.random((5, 2, 3))
b /= np.sum(b)

#### 6. Print *b*.


In [124]:
# print the array
print(b)
#check if sum == 1
b.sum()

[[[0.00722858 0.06639987 0.01180412]
  [0.01304562 0.03810253 0.02805066]]

 [[0.00496531 0.03308242 0.06269374]
  [0.00056854 0.0436536  0.01854728]]

 [[0.03554708 0.00831685 0.0138498 ]
  [0.06295516 0.06260308 0.02717967]]

 [[0.04257645 0.05794493 0.06701127]
  [0.03503332 0.00753659 0.05669649]]

 [[0.01012719 0.01141132 0.05312096]
  [0.06147561 0.02594339 0.03252857]]]


1.0

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [125]:
# your code here
# Comparing the size of randomly generated array A and randomonly
# generated but limited to sum == 1, array B.
if np.size(a) == np.size(b):
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [127]:
# your answer here
# No, the shapes are different. A Value error pops up:
    #ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
# np.add(a,b)

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [132]:
# your code here
c = b.reshape(2, 3, 5)
print(c)

[[[0.00722858 0.06639987 0.01180412 0.01304562 0.03810253]
  [0.02805066 0.00496531 0.03308242 0.06269374 0.00056854]
  [0.0436536  0.01854728 0.03554708 0.00831685 0.0138498 ]]

 [[0.06295516 0.06260308 0.02717967 0.04257645 0.05794493]
  [0.06701127 0.03503332 0.00753659 0.05669649 0.01012719]
  [0.01141132 0.05312096 0.06147561 0.02594339 0.03252857]]]


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [135]:
# your code/answer here
d = np.add(a, c)
# the arrays share the same shape hence the values can be added

[[[0.41506573 0.50985743 0.22296746 0.98926772 0.04251454]
  [0.04175623 0.89153851 0.30029574 0.7418723  0.31646071]
  [0.65375362 0.6903672  0.82222369 0.34269193 0.32277137]]

 [[0.41129207 0.97579761 0.47226179 0.3774885  0.83927589]
  [0.26242341 0.49183348 0.64197982 0.66483571 0.48056155]
  [0.09916304 0.19604033 0.88178381 0.90350933 0.68846553]]]


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [145]:
# your code/answer here
print(a,d)

[[[0.40783714 0.44345756 0.21116334 0.9762221  0.00441201]
  [0.01370557 0.8865732  0.26721333 0.67917855 0.31589216]
  [0.61010002 0.67181993 0.78667661 0.33437508 0.30892157]]

 [[0.34833691 0.91319453 0.44508212 0.33491205 0.78133097]
  [0.19541215 0.45680016 0.63444324 0.60813922 0.47043436]
  [0.08775172 0.14291936 0.8203082  0.87756593 0.65593696]]] [[[0.41506573 0.50985743 0.22296746 0.98926772 0.04251454]
  [0.04175623 0.89153851 0.30029574 0.7418723  0.31646071]
  [0.65375362 0.6903672  0.82222369 0.34269193 0.32277137]]

 [[0.41129207 0.97579761 0.47226179 0.3774885  0.83927589]
  [0.26242341 0.49183348 0.64197982 0.66483571 0.48056155]
  [0.09916304 0.19604033 0.88178381 0.90350933 0.68846553]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [147]:
# your code here
e = np.multiply(a,c)
print(e)

[[[0.00294808 0.02944552 0.0024926  0.01273542 0.00016811]
  [0.00038445 0.00440211 0.00884006 0.04258025 0.0001796 ]
  [0.02663306 0.01246043 0.02796405 0.00278095 0.0042785 ]]

 [[0.02192961 0.05716879 0.01209719 0.01425937 0.04527417]
  [0.01309482 0.01600323 0.00478154 0.03447936 0.00476418]
  [0.00100136 0.00759201 0.05042895 0.02276704 0.02133669]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [149]:
# your code/answer here
a == e
# No, because a multiplication to the values of a was added.

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [159]:
# your code here
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max,d_min,d_mean)

0.9892677193997281 0.041756231444941685 0.5230038685064194


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [165]:
# your code here
f = np.empty((2, 3, 5))
print(f)

[[[0.00294808 0.02944552 0.0024926  0.01273542 0.00016811]
  [0.00038445 0.00440211 0.00884006 0.04258025 0.0001796 ]
  [0.02663306 0.01246043 0.02796405 0.00278095 0.0042785 ]]

 [[0.02192961 0.05716879 0.01209719 0.01425937 0.04527417]
  [0.01309482 0.01600323 0.00478154 0.03447936 0.00476418]
  [0.00100136 0.00759201 0.05042895 0.02276704 0.02133669]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [189]:
# your code here
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [190]:
# your code here
print(d)
print(f)

[[[0.41506573 0.50985743 0.22296746 0.98926772 0.04251454]
  [0.04175623 0.89153851 0.30029574 0.7418723  0.31646071]
  [0.65375362 0.6903672  0.82222369 0.34269193 0.32277137]]

 [[0.41129207 0.97579761 0.47226179 0.3774885  0.83927589]
  [0.26242341 0.49183348 0.64197982 0.66483571 0.48056155]
  [0.09916304 0.19604033 0.88178381 0.90350933 0.68846553]]]
[[[ 25.  25.  25. 100.  25.]
  [  0.  75.  25.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[ 25.  75.  25.  25.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 25.  25.  75.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [201]:
# your code here

ValueError: could not convert string to float: 'A'