# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
np.version.version

'1.18.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
# Method 1
a = np.random.random((2,3,5))

In [4]:
# Method 2
a = np.random.uniform(low=0, high=1, size=(2,3,5))

In [5]:
# Method 3
a = np.empty((2,3,5))

In [6]:
# Method 4
a = np.random.rand(2,3,5)

#### 4. Print *a*.


In [7]:
print(a)

[[[0.96608579 0.81377672 0.30628451 0.39738752 0.41215566]
  [0.55781158 0.7285995  0.19958187 0.03655434 0.75599994]
  [0.67214    0.91843432 0.20059774 0.73185349 0.78999461]]

 [[0.44367442 0.40471251 0.63671605 0.7245637  0.82159393]
  [0.46034494 0.68864485 0.1758968  0.77816694 0.94187328]
  [0.92748391 0.57819149 0.76583617 0.31739499 0.25251642]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [8]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [9]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [10]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [11]:
# arrays a and b can not be added, because not same shape

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [12]:
c = b.reshape(2,3,5)
print(c)
print(c.shape)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [13]:
d = a + c
# because the arrays now have the same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [14]:
print(a)
print('\n')
print(d)
# variable d = variable c +1 for each element

[[[0.96608579 0.81377672 0.30628451 0.39738752 0.41215566]
  [0.55781158 0.7285995  0.19958187 0.03655434 0.75599994]
  [0.67214    0.91843432 0.20059774 0.73185349 0.78999461]]

 [[0.44367442 0.40471251 0.63671605 0.7245637  0.82159393]
  [0.46034494 0.68864485 0.1758968  0.77816694 0.94187328]
  [0.92748391 0.57819149 0.76583617 0.31739499 0.25251642]]]


[[[1.96608579 1.81377672 1.30628451 1.39738752 1.41215566]
  [1.55781158 1.7285995  1.19958187 1.03655434 1.75599994]
  [1.67214    1.91843432 1.20059774 1.73185349 1.78999461]]

 [[1.44367442 1.40471251 1.63671605 1.7245637  1.82159393]
  [1.46034494 1.68864485 1.1758968  1.77816694 1.94187328]
  [1.92748391 1.57819149 1.76583617 1.31739499 1.25251642]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [15]:
e = a * c

print(e)

[[[0.96608579 0.81377672 0.30628451 0.39738752 0.41215566]
  [0.55781158 0.7285995  0.19958187 0.03655434 0.75599994]
  [0.67214    0.91843432 0.20059774 0.73185349 0.78999461]]

 [[0.44367442 0.40471251 0.63671605 0.7245637  0.82159393]
  [0.46034494 0.68864485 0.1758968  0.77816694 0.94187328]
  [0.92748391 0.57819149 0.76583617 0.31739499 0.25251642]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [16]:
print(e == a)
print('\n')
print(a.all() == e.all())

# array multiplied with 1 for each element gives same result (both for all elements as array as whole)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [17]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9660857867864636
1.0365543395851948
1.5801622663573283


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [18]:
f = np.empty((2,3,5))
print(f)

[[[0.96608579 0.81377672 0.30628451 0.39738752 0.41215566]
  [0.55781158 0.7285995  0.19958187 0.03655434 0.75599994]
  [0.67214    0.91843432 0.20059774 0.73185349 0.78999461]]

 [[0.44367442 0.40471251 0.63671605 0.7245637  0.82159393]
  [0.46034494 0.68864485 0.1758968  0.77816694 0.94187328]
  [0.92748391 0.57819149 0.76583617 0.31739499 0.25251642]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [19]:
#check if conditions give boolean output in array
variable25 = (d > d_min) & (d < d_mean)
print(variable25)
print('\n')

f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)

[[[False False  True  True  True]
  [ True False  True False False]
  [False False  True False False]]

 [[ True  True False False False]
  [ True False  True False False]
  [False  True False  True  True]]]


[[[100.  75.  25.  25.  25.]
  [ 25.  75.  25.   0.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  25.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [20]:
print(d)
print('\n')
print(f)

[[[1.96608579 1.81377672 1.30628451 1.39738752 1.41215566]
  [1.55781158 1.7285995  1.19958187 1.03655434 1.75599994]
  [1.67214    1.91843432 1.20059774 1.73185349 1.78999461]]

 [[1.44367442 1.40471251 1.63671605 1.7245637  1.82159393]
  [1.46034494 1.68864485 1.1758968  1.77816694 1.94187328]
  [1.92748391 1.57819149 1.76583617 1.31739499 1.25251642]]]


[[[100.  75.  25.  25.  25.]
  [ 25.  75.  25.   0.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 25.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [21]:
g = np.array(f, dtype = 'str')

g[(d > d_min) & (d < d_mean)] = "B"
g[(d > d_mean) & (d < d_max)] = "D"
g[d == d_mean] = "C"
g[d == d_min] = "A"
g[d == d_max] = "E"

print(g)

[[['E' 'D' 'B' 'B' 'B']
  ['B' 'D' 'B' 'A' 'D']
  ['D' 'D' 'B' 'D' 'D']]

 [['B' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'D' 'B' 'B']]]
