# Supervised Learning: Classification

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv('https://raw.githubusercontent.com/loukjsmalbil/datasets_ws/master/titanic_preprocessed.csv')
data = data.drop(columns=['male'])

URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)>

In [ ]:
data.head()

# Logistic Regression

## Data Processing (LR)


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
y = data['survived'] 

In [ ]:
y

In [ ]:
X = data.drop('survived', axis=1)  

In [ ]:
X

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

## Train the Model (LR)

In [11]:
from sklearn.linear_model import LogisticRegression 

In [12]:
model = LogisticRegression()

In [13]:
model.fit(X_train, y_train)

LogisticRegression()

## Test the Model

In [14]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [15]:
y_pred = model.predict(X_test)

In [17]:
pd.DataFrame({'test':y_test, 'predicted':y_pred})

test  predicted
890     0          0
398     0          0
700     1          1
660     1          0
445     1          1
..    ...        ...
827     1          1
141     1          1
111     0          1
775     0          0
470     0          0

[179 rows x 2 columns]

In [18]:
confusion_matrix(y_test, y_pred)

# TP = 97
# FN = 15
# FP = 14
# TN = 53

array([[100,  14],
       [ 19,  46]])

In [19]:
accuracy_score(y_test, y_pred)

0.8156424581005587

# Decision Trees

## Data Processing (DT)


In [20]:
data = pd.read_csv('https://raw.githubusercontent.com/loukjsmalbil/datasets_ws/master/titanic_preprocessed.csv')
data = data.drop(columns=['male'])

In [21]:
y = data['survived'] 
X = data.drop('survived', axis=1)  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

## Train the Model (DT)

In [22]:
from sklearn import tree

In [23]:
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)

DecisionTreeClassifier()

## Test the Model (DT)

In [24]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('\n')
print(accuracy_score(y_test, y_pred))

[[85 17]
 [23 54]]


0.776536312849162


In [25]:
pd.DataFrame({'test':y_test, 'predicted':y_pred})

test  predicted
184     1          1
777     1          1
696     0          0
630     1          0
346     1          1
..    ...        ...
668     0          0
150     0          0
526     1          1
623     0          0
719     0          0

[179 rows x 2 columns]

# Support Vector Machines

## Data Processing (SVM)




In [26]:
data = pd.read_csv('https://raw.githubusercontent.com/loukjsmalbil/datasets_ws/master/titanic_preprocessed.csv')
data = data.drop(columns=['male'])

In [27]:
y = data['survived'] 
X = data.drop('survived', axis=1)  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

## Train the Model (SVM)

In [28]:
from sklearn import svm

In [29]:
model = svm.SVC()
model.fit(X_train, y_train)

SVC()

## Test the Model (SVM)

In [30]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('\n')
print(accuracy_score(y_test, y_pred))

[[102   3]
 [ 55  19]]


0.6759776536312849


In [31]:
pd.DataFrame({'test':y_test, 'predicted':y_pred})

test  predicted
578     0          0
429     1          0
408     0          0
422     0          0
213     0          0
..    ...        ...
608     1          0
743     0          0
587     1          1
740     1          0
151     1          1

[179 rows x 2 columns]

# k-Nearest Neighbour

## Data Processing (kNN)


In [32]:
data = pd.read_csv('https://raw.githubusercontent.com/loukjsmalbil/datasets_ws/master/titanic_preprocessed.csv')
data = data.drop(columns=['male'])

In [33]:
y = data['survived'] 
X = data.drop('survived', axis=1)  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

## Train the Model (kNN)

In [34]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
model = KNeighborsClassifier(n_neighbors=2)
model.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=2)

## Test the Model (kNN)

In [36]:
y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('\n')
print(accuracy_score(y_test, y_pred))

[[100   9]
 [ 38  32]]


0.7374301675977654


In [37]:
pd.DataFrame({'test':y_test, 'predicted':y_pred})

test  predicted
566     0          0
24      0          1
429     1          0
661     0          0
248     1          0
..    ...        ...
406     0          0
256     1          0
422     0          0
556     1          0
261     1          0

[179 rows x 2 columns]

In [38]:
# 0.7094972067039106. k = 3
# 0.6871508379888268. k =10
# 0.7094972067039106. k = 8
# 0.6983240223463687  k = 2

## Bonus: Predicting Heart Disease 

In [39]:
heart = pd.read_csv('heart.csv')

In [40]:
heart.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [42]:
y = heart['target'] 
X = heart.drop('target', axis=1)  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)

### Logistic Regression

In [44]:
model = LogisticRegression()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('\n')
print(accuracy_score(y_test, y_pred))

[[24  6]
 [ 2 29]]


0.8688524590163934


### Random Forest

In [46]:
from sklearn.ensemble import RandomForestClassifier

In [47]:
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('\n')
print(accuracy_score(y_test, y_pred))

[[20 10]
 [ 2 29]]


0.8032786885245902


### Support Vector Machine

In [48]:
model = svm.SVC()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

y_pred = model.predict(X_test)
print(confusion_matrix(y_test, y_pred))
print('\n')
print(accuracy_score(y_test, y_pred))

[[16 14]
 [ 5 26]]


0.6885245901639344
